version: '3'

services:

  app:

    # TO RUN YOUR CODE (e.g.):
    # ------------------------
    # docker compose run --rm app
    # ... or ...
    # bash first   : docker compose run --rm app bash
    # and then app : python -B main.py

    # TO RUN CODE TO BE REVIEWED (e.g.):
    # ----------------------------------
    # docker compose run --rm app python -B main.py --review=1
    # ... or ...
    # bash first   : docker compose run --rm app bash
    # and then app : python -B main.py --review=1

    image: nosql-2024:ex1.a
    build:
      dockerfile: ./Dockerfile
    command: python -B main.py
    volumes:
      - ./app:/home/app
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo}
    profiles:
      - do-not-start-by-default

  mongo:

    # TO START MONGO CONTAINER
    # ------------------------
    # docker compose up -d    # to see log messages omit '-d'

    # TO SHUT DOWN MONGO CONTAINER
    # ----------------------------
    # docker compose down 

    # TO RUN MONGO SHELL IN MONGO CONTAINER
    # -------------------------------------
    # docker compose exec mongo mongosh 

    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - nosql-2024-ex1a-mongo-db-data:/data/db

volumes:
  nosql-2024-ex1a-mongo-db-data:

